const paths = {
  home: '/',
  login: '/login',
  forgotPassword: '/forgot-password',
  lookingForPartners: '/looking-for-partners',
  billing: '/billing',
  businessProfile: '/business-profile',
  businessProfileSettings: '/business-profile-settings',
  businessRegistration: '/business-registration',
  businessRegStep1: '/business-registration/step-1',
  businessRegStep2: '/business-registration/step-2',
  businessRegStep3: '/business-registration/step-3',
  businessRegStep4: '/business-registration/step-4',
  partnerLocator: '/partner-locator',
  consultantLocator: '/consultant-locator',
  consultantProfile: '/consultant-profile',
  consultantProfileSettings: '/consultant-profile-settings',
  consultantRegistration: '/consultant-registration',
  consultantRegStep1: '/consultant-registration/step-1',
  consultantRegStep2: '/consultant-registration/step-2',
  consultantRegStep3: '/consultant-registration/step-3',
  howItWorks: '/how-it-works',
  terms: '/terms-of-use',
  whatIsYourIndustry: '/what-is-your-industry',
  contacts: '/contact-us',
  step1: '/step-1',
  step2: '/step-2',
  step3: '/step-3',
  step4: '/step-4',
};

export default paths;
